# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSv_bPxtyxibwqMdek0lIpx52JybIom2
"""

!sudo apt update
!sudo apt install tesseract-ocr tesseract-ocr-chi-tra

!pip install pytesseract

import pytesseract
from PIL import Image
import cv2
from google.colab.patches import cv2_imshow

# 1. 設定圖片路徑
image_path = "wish.png"

# 2. 讀取並顯示圖片 (確認讀取成功)
img = cv2.imread(image_path)
cv2_imshow(img)

# 3. OCR 核心辨識
# lang='chi_tra+eng' 代表同時搜尋繁體中文與英文
# config='--psm 3' 常用於自動分割區塊
text = pytesseract.image_to_string(img, lang='chi_tra+eng', config='--psm 3')

print("\n--- OCR 辨識結果 ---")
print(text)

# 4. 存成文字檔
with open("result.txt", "w", encoding="utf-8") as f:
    f.write(text)
    print("\n[系統提示] 結果已儲存至 result.txt")